Soares/use port channel
informalsystems/ibc-rs pull request #1052
Opened 2021-06-07 08:29 UTC by soareschen

Partially Closes: #1001

## Description

This PR replaces the use of `(PortId, ChannelId)` to use the `PortChannelId` struct.

______

For contributor use:

- [ ] Updated the __Unreleased__ section of [CHANGELOG.md](https://github.com/informalsystems/ibc-rs/blob/master/CHANGELOG.md) with the issue.
- [ ] If applicable: Unit tests written, added test to CI.
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Updated relevant documentation (`docs/`) and code comments.
- [ ] Re-reviewed `Files changed` in the Github PR explorer.

2021-06-07 10:39 UTC, romac commented
@adizere Can you describe the reasoning behind the suggested change that this PR addresses?

> Some improvements can be done for channel-related methods, specifically when both a ChannelId and a PortId are provided as input (for example here), and instead of these two types a single PortChannelId should be used.

I am not sure I see what using a struct over a tuple brings us here?

---

The problem I have with using `PortChannelId` instead of `(PortId, ChannelId)` is that in both cases we often need to clone the `PortId` and `ChannelId` when only a reference would be enough, eg. calling

```rust
fn get_something(key: &(PortId, ChannelId)) -> Foo {}
```

when one has owned `PortId` and `ChannelId` requires doing:

```rust
get_something(&(port_id.clone(), channel_id.clone())
```

Same with

```rust
fn get_something(key: &PortChannelId) -> Foo {}

get_something(& PortChannelId::new(port_id.clone(), channel_id.clone()))
```

If we stick with tuples (which I believe are fine for the use case of bundling two values to be used as a lookup key), we could instead have this API:

```rust
fn get_something(key: (&PortId, &ChannelId)) -> Foo {}

get_something((&port_id, &channel_id))
```

and avoid unnecessary clones.

Admittedly, we could introduce a `PortChannelIdRef` struct which holds references to its components, but again I am not sure what it really gets us over a tuple:

```rust
struct PortChannelIdRef<'a> {
  port_id: &'a PortId,
  channel_id: &'a ChannelId
}
```

I guess the question of *struct vs tuple* and *owned data vs references* are orthogonal, but I feel like using tuples+references is the simpler solution here. Happy to hear otherwise though.

@soareschen What are your thoughts on this? My apologies for nitpicking your PR when the culprit here is me not catching this and raising this discussion when the issue was opened.

2021-06-07 10:56 UTC, romac requested changes
https://github.com/informalsystems/ibc-rs/pull/1052#issuecomment-855816230

2021-06-07 11:23 UTC, soareschen commented
I have actually tried to compare the two approaches, and I don't find significant advantage between either of them. Either way we are doing cloning in quite a number of places already, and I think it is premature to try to optimize the clones away.

The main issue I see is in the final implementation of the use of the port channel ID, which are in structures such as `HashMap<(PortId, ChannelId, Sequence), Receipt>`. So even if we pass by reference in the function calls, eventually clones have to be made in order to construct the tuple as a value and pass a single reference to `HashMap`. As a result, it is always either the caller having to do the clone by constructing `(PortId, ChannelId, Sequence)` and pass by reference, or the callee having to do the clone by accepting `&PortId, &ChannelId, &Sequence` and then construct the tuple `(PortId, ChannelId, Sequence)`.

We probably don't need to worry about the cost of cloning for now, since they are mainly consist of short string identifiers. It should be unlikely we will hit performance bottleneck on that part for the time being.

2021-06-07 11:44 UTC, soareschen commented
Btw there will be less need for cloning once we refactor structs like `Packet` to use `PortChannelId` directly instead of having separate `PortId` and `ChannelId` fields. Do you think we should also refactor that in this PR to make it slightly more efficient? Or I can do it in a follow up PR.

2021-06-07 15:45 UTC, romac commented
> The main issue I see is in the final implementation of the use of the port channel ID, which are in structures such as HashMap<(PortId, ChannelId, Sequence), Receipt>. So even if we pass by reference in the function calls, eventually clones have to be made in order to construct the tuple as a value and pass a single reference to HashMap.

Right, I hadn't noticed this. Nevermind then :)

> We probably don't need to worry about the cost of cloning for now, since they are mainly consist of short string identifiers. It should be unlikely we will hit performance bottleneck on that part for the time being.

I am not very concerned either, as you say we already clone a lot of stuff. Still, given that the `ibc` crate will eventually be `no-std + alloc` compatible, we might want to give it some special attention when it comes to allocating memory, as one might eventually want to use it in memory constrained environments, or in environments where memory allocations are particularly costly.

I still don't really see what we gain by grouping the port and channel id in a single (awkwardly named*) struct where a tuple, but will not oppose it as my other points are moot.

\* the fact that there is no obvious good name for this struct (at least to me) kinda tells me that it's not needed, but I am happy to proven wrong if anyone finds a good name. It's not required for this PR to be merged though.

2021-06-07 15:56 UTC, romac commented
Actually, after looking at the code again, I wonder why we don't just do 

```rust
fn get_next_sequence_send(&self, port_id: &PortId, channel_id: &ChannelId) -> Option<Sequence>
```

instead of using either a tuple (like we do currently) or a struct (like this PR suggests)?

This is more idiomatic, and while it won't avoid the problem with the `HashMap` that you mention, the latter is an implementation detail which should not interfere with the abstract API.

Sorry for being a pain about this, and changing my mind, but as the `ibc` crate will likely end up being the most widely used crate in the ibc-rs project, I would like to make sure we expose nice, idiomatic, easy to use APIs.

2021-06-07 19:35 UTC, adizere commented
The idea of the type `PortChannel` replacing the two types `PortId + ChannelId` came up some time ago, when Cezara first implemented the ICS04 handlers and we noticed that theres some potential for capturing these two types and reducing the number of parameters. Here's some background: #745. Based on the discussion in that issue, I recently opened an issue in cosmos/ibc (https://github.com/cosmos/ibc/issues/583) to implement the change upstream. The upstream change is pending, and not clear if it's going to happen at all, so maybe that will help inform us here if we should do it in the first place.

The rationale is to simplify some interfaces & calls. It would reduce the number of parameters, and would make it explicit that there is a special relation between a `Port` and a `Channel` identifier.

The idea of the new type is not set in stone, of course. @romac thanks for insisting on this, since it might actually prove that the original definitions from the spec ([core/ics-004](https://github.com/cosmos/ibc/tree/master/spec/core/ics-004-channel-and-packet-semantics#store-paths))
```rust
fn get_next_sequence_send(&self, port_id: &PortId, channel_id: &ChannelId) -> Option<Sequence>
```

... are actually the best way to do it.


> Btw there will be less need for cloning once we refactor structs like Packet to use PortChannelId directly instead of having separate PortId and ChannelId fields. Do you think we should also refactor that in this PR to make it slightly more efficient? 

I agree with you, Soares. But let's first try reach a consensus whether this new type is valuable at all. And if so, let's modify the `Packet` (and others) separately.

2021-06-07 19:49 UTC, soareschen commented
No problem, we can discuss further on how to better design the interface. I think with the PR in place we are better informed what the changes would look like.

I think an advantage of having a single type like `PortChannelId` is that it makes it more unlikely to accidentally mix up the use of different `portId` / `channelId` pairs. Other than that, it was introduced in #861 because we need it as a newtype for custom derivation the `Serialize` and `Deserialize` traits, and we can't implement that with the tuple type.

Otherwise, I am fine with passing them as two separate parameters as well.

2021-06-07 20:58 UTC, romac commented
Thanks both, you are both making compelling arguments. I like the `Socket` name mentioned in the `cosmos/ibc` issue. Having a good name for the compound data structure makes it more compelling to me, as does the argument for it making it harder to mix up different port and channel combinations. I vote for this change, but would suggest we wait until it gets upstream as well before merging this. What do you think?

2021-06-09 10:43 UTC, adizere commented
Closing this with note:

- wait for ibc-go to adopt `Socket` terminology
- redo the PR with the new name

2021-06-09 10:43 UTC, closed without merging