Dr def legacy error
informalsystems/ibc-rs pull request #1167
Opened 2021-07-09 14:25 UTC by DaviRain-Su

> Use a wrapper struct for Box<dyn std::error::Error> for remaining errors not updated by Use flex-error to define errors #988.

> PR Use flex-error to define errors #988 has removed most of the uses of Box<dyn std::error::Error>, however, there are still a few places remaining that are still using std::error::Error.
PR Enable IBC to Support no-std #1109 attempts to polyfill std::error::Error by aliasing it to a DummyError struct in no-std mode. However doing so does not prevent dependencies from constructing Box<dyn std::error::Error>, which would prevent no-std from being supported. On the other hand, if we have control of all places that produce Box<dyn std::error::Error>, we can also modify them to return something other than Box<dyn std::error::Error>.
I'd propose that we define a type like LegacyError, which is either a newtype wrapper to Box<dyn std::error::Error> in std mode or a newtype wrapper to String in no-std mode. By always using a newtype wrapper, we can avoid accidental implicit coercion from Box<dyn std::error::Error> to LegacyError in std mode, which will prevent no-std mode to work.
There should be a Cargo separate feature flag to switch between the two modes to LegacyError. The purpose is to be able to test the two modes of LegacyError without fully activating no-std.
This change can be done inside Enable IBC to Support no-std #1109 Use flex-error to define errors #988, or a follow-up PR to Enable IBC to Support no-std #1109 Use flex-error to define errors #988. It is also possible to make this change against the master, although there will be much more changes needed.

I deine a `LegacyError` replace `Box<dyn std::error::Error>`.

______

For contributor use:

- [ ] Updated the __Unreleased__ section of [CHANGELOG.md](https://github.com/informalsystems/ibc-rs/blob/master/CHANGELOG.md) with the issue.
- [ ] If applicable: Unit tests written, added test to CI.
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Updated relevant documentation (`docs/`) and code comments.
- [ ] Re-reviewed `Files changed` in the Github PR explorer.

2021-07-12 15:20 UTC, romac commented
@DaviRain-Su What's the status on this PR? I am asking because it does not compile at the moment.

@soareschen What's your take on this?

2021-07-12 19:26 UTC, soareschen requested changes

2021-07-12 19:26 UTC, soareschen commented on modules/src/ics07_tendermint/error.rs
> +pub struct StdError {
There is no need for an additional `StdError` struct.

2021-07-12 19:26 UTC, soareschen commented on modules/src/ics07_tendermint/error.rs
> +pub enum LegacyError {
> I'd propose that we define a type like LegacyError, which is either a newtype wrapper to Box in std mode or a newtype wrapper to String in no-std mode.

What I meant is more of:

```rust
struct LegacyError {
  #[cfg(feature = "std_err")]
  error: Box<dyn std::error::Error + Send + Sync>,

  #[cfg(not(feature = "std_err"))]
  error: String,
}
```

2021-07-12 19:26 UTC, soareschen commented on modules/src/ics07_tendermint/error.rs
> +    fn as_str(&self) -> String {
We can have a [`ToString`](https://doc.rust-lang.org/std/string/trait.ToString.html) implementation of `LegacyError`.

2021-07-12 19:26 UTC, soareschen commented on modules/src/ics07_tendermint/error.rs
> +impl From<Box<dyn std::error::Error + Send + Sync>> for LegacyError {
We should have a `From<String>` instance for `LegacyError` as well.

2021-07-12 19:26 UTC, soareschen commented on modules/src/ics07_tendermint/header.rs
> +                .map_err(|val : Box<dyn std::error::Error + Send + Sync> | val.into())
I think it should be something like

```rust
  .try_into()
  .map_err(|e| error::invalid_raw_header_error(e.into()))
```

2021-07-12 19:26 UTC, soareschen commented on modules/Cargo.toml
> +test_no_std = []
Let's feature gate the `std::error::Error` mode as the `"std_err"` feature. We can later set the `"std"` feature to enable the `"std_err"` feature.

2021-07-17 12:53 UTC, DaviRain-Su commented
> @DaviRain-Su What's the status on this PR? I am asking because it does not compile at the moment.
> 
> @soareschen What's your take on this?

run this command :  cargo check --features std_err

2021-07-26 19:25 UTC, closed without merging