Yuji/cleanup errors
informalsystems/ibc-rs pull request #1334
Opened 2021-09-08 10:16 UTC by yito88

Closes: #1333 

## Description
- Add `Ics02Error` and `Ics03Error` to `Ics04Error`
- Give the port ID and the channel ID to `MissingNext*Seq` error
- Remove redundant errors

______

For contributor use:

- [ ] Added a changelog entry, using [`unclog`](https://github.com/informalsystems/unclog).
- [ ] If applicable: Unit tests written, added test to CI.
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Updated relevant documentation (`docs/`) and code comments.
- [ ] Re-reviewed `Files changed` in the Github PR explorer.

2021-09-08 16:24 UTC, hu55a1n1 requested changes

2021-09-08 16:24 UTC, hu55a1n1 commented on modules/src/ics04_channel/error.rs
> +
```suggestion
```
I would suggest removing this variant from here and reusing `Ics03Connection::Ics02Client`.

2021-09-08 16:24 UTC, hu55a1n1 commented on modules/src/mock/context.rs
> +        ClientReader::consensus_state(self, client_id, height).map_err(Ics04Error::ics02_client)
```suggestion
        ClientReader::consensus_state(self, client_id, height)
            .map_err(|e| Ics04Error::ics03_connection(Ics03Error::ics02_client(e)))
```

2021-09-08 16:24 UTC, hu55a1n1 commented on modules/src/mock/context.rs
> +        ClientReader::client_state(self, client_id).map_err(Ics04Error::ics02_client)
```suggestion
        ClientReader::client_state(self, client_id)
            .map_err(|e| Ics04Error::ics03_connection(Ics03Error::ics02_client(e)))
```

2021-09-09 11:51 UTC, hu55a1n1 requested changes
Thanks @yito88! Just one more thing - compilation is currently failing for tests. Here's a fix ->
```patch
diff --git a/modules/src/ics04_channel/handler/chan_open_try.rs b/modules/src/ics04_channel/handler/chan_open_try.rs
index dd71eb65..5191e0ef 100644
--- a/modules/src/ics04_channel/handler/chan_open_try.rs
+++ b/modules/src/ics04_channel/handler/chan_open_try.rs
@@ -370,12 +370,16 @@ mod tests {
                 msg: ChannelMsg::ChannelOpenTry(msg.clone()),
                 want_pass: false,
                 match_error: Box::new(|e| match e {
-                    error::ErrorDetail::Ics02Client(e) => {
+                    error::ErrorDetail::Ics03Connection(e) => {
                         assert_eq!(
                             e.source,
-                            ics02_error::ErrorDetail::ClientNotFound(
-                                ics02_error::ClientNotFoundSubdetail {
-                                    client_id: ClientId::new(ClientType::Mock, 45).unwrap()
+                            ics03_error::ErrorDetail::Ics02Client(
+                                ics03_error::Ics02ClientSubdetail {
+                                    source: ics02_error::ErrorDetail::ClientNotFound(
+                                        ics02_error::ClientNotFoundSubdetail {
+                                            client_id: ClientId::new(ClientType::Mock, 45).unwrap()
+                                        }
+                                    )
                                 }
                             )
                         );
```
Once #1283 is merged, it would be great if you could rebase on/merge with master.

2021-09-10 08:41 UTC, yito88 commented
Thank you for reviewing and fixing!
I've rebased on master.

2021-09-10 08:45 UTC, hu55a1n1 approved these changes

2021-09-14 08:00 UTC, adizere approved these changes
Nice idea to consolidate the errors like this. Great work!

2021-09-14 08:01 UTC, merged