Fix typos and update broken links in Documentation
informalsystems/ibc-rs pull request #1385
Opened 2024-12-25 11:52 UTC by Pricstas

This pull request addresses minor issues in the project documentation by fixing typos and updating outdated links. 
The following changes were made:

#### Typographical Fixes:
1. **File:** `1083-bump-serde-json.md`
   - Corrected "an stack overflow" to "a stack overflow."

#### Link Updates:
2. **File:** `1295-move-cosmwasm-impls-to-separate-workspace.md`
   - Updated broken link to issue #1295:
     - **Old:** `https://github.com/cosmos/ibc-rs/issue/1295`
     - **New:** `https://github.com/cosmos/ibc-rs/issues/1295`

3. **File:** `ibc-clients/README.md`
   - Updated outdated link for CosmWasm implementations:
     - **Old:** `https://github.com/informalsystems/cosmwasm-ibc/ibc-clients/ics07-tendermint`
     - **New:** `https://github.com/cosmos/sp1-ics07-tendermint`

---

### PR author checklist:
- [x] Added changelog entry using [`unclog`](https://github.com/informalsystems/unclog).
- [ ] Added tests (N/A for documentation changes).
- [x] Updated relevant documentation and links.
- [x] Tagged reviewer to shepherd this PR.

---

### Reviewer checklist:
- [ ] Reviewed `Files changed` for correctness and consistency.
- [ ] Verified updated links.
- [ ] Confirmed no additional changes are necessary.

2024-12-26 14:39 UTC, rnbguy commented on .changelog/v0.51.0/bug-fixes/1083-bump-serde-json.md
> +- [ibc] Upgrade `serde_json` to "1.0.1" to address a stack overflow issue
This needs to be synced in `CHANGELOG.md` too.

2024-12-26 14:40 UTC, rnbguy requested changes

2024-12-26 14:40 UTC, rnbguy commented on .changelog/v0.51.0/bug-fixes/1083-bump-serde-json.md
> +- [ibc] Upgrade `serde_json` to "1.0.1" to address a stack overflow issue
This needs to be synced in `CHANGELOG.md` too.

2024-12-26 14:40 UTC, rnbguy commented on .changelog/v0.54.0/improvements/1295-move-cosmwasm-impls-to-separate-workspace.md
> +MSRV from `cosmwasm`. ([\#1295](https://github.com/cosmos/ibc-rs/issues/1295))
Needs sync with `CHANGELOG.md`.

2024-12-26 14:40 UTC, rnbguy commented on ibc-clients/README.md
> +- [ibc-client-tendermint-cw](https://github.com/cosmos/sp1-ics07-tendermint): CosmWasm
The correct link is: https://github.com/informalsystems/cosmwasm-ibc/tree/main/ibc-clients/ics07-tendermint

2025-01-07 10:28 UTC, Pricstas commented on .changelog/v0.51.0/bug-fixes/1083-bump-serde-json.md
> +- [ibc] Upgrade `serde_json` to "1.0.1" to address a stack overflow issue
Updated the CHANGELOG.md to reflect the corrections made in the documentation, including the typographical fixes and link updates

2025-01-07 10:28 UTC, Pricstas commented on .changelog/v0.54.0/improvements/1295-move-cosmwasm-impls-to-separate-workspace.md
> +MSRV from `cosmwasm`. ([\#1295](https://github.com/cosmos/ibc-rs/issues/1295))
Updated the CHANGELOG.md to reflect the corrections made in the documentation, including the typographical fixes and link updates

2025-01-07 10:29 UTC, Pricstas commented on ibc-clients/README.md
> +- [ibc-client-tendermint-cw](https://github.com/cosmos/sp1-ics07-tendermint): CosmWasm
Corrected the link in `ibc-clients/README.md` to the correct URL

2025-01-07 10:30 UTC, Pricstas commented
Hi @rnbguy 

Thank you for the review! I have made the following changes as requested:

- **Synced changes with CHANGELOG.md**: Updated the changelog to reflect the corrections made in the documentation, including the typographical fixes and link updates.
- **Corrected the link** in `ibc-clients/README.md` to the correct URL: [https://github.com/informalsystems/cosmwasm-ibc/tree/main/ibc-clients/ics07-tendermint](https://github.com/informalsystems/cosmwasm-ibc/tree/main/ibc-clients/ics07-tendermint).

The changes are now ready for your approval. Thank you!

2025-01-07 10:32 UTC, rnbguy approved these changes

2025-01-07 10:33 UTC, merged