Added docs for `unreceived_acknowledgements` and `unreceived_packets`
informalsystems/ibc-rs pull request #2157
Opened 2022-04-28 11:03 UTC by adizere

This answers a user's question from Discord.
I originally wanted to document these details in the guide, but opted for code-level docs since this seems more appropriate.

Tagged @seanchen1991 as reviewer since we're both monitoring Discord and he has the most context.

______

### PR author checklist:
- [ ] Added changelog entry, using [`unclog`](https://github.com/informalsystems/unclog).
- [ ] Added tests: integration (for Hermes) or unit/mock tests (for modules). 
- [ ] Linked to GitHub issue.
- [ ] Updated code comments and documentation (e.g., `docs/`).

### Reviewer checklist:

- [ ] Reviewed `Files changed` in the GitHub PR explorer.
- [ ] Manually tested (in case integration/unit/mock tests are absent).

2022-04-28 19:19 UTC, mzabaluev approved these changes
Looks good!

2022-04-28 19:38 UTC, seanchen1991 requested changes

2022-04-28 19:38 UTC, seanchen1991 commented on relayer/src/chain/counterparty.rs
> +/// This method expects an [`IdentifiedChannelEnd`] plus a pair of
I would flip the order of these first two sentences; start off with what this method does, and then mention what the method expects.

2022-04-28 19:38 UTC, seanchen1991 commented on relayer/src/chain/counterparty.rs
> +/// This method expects an [`IdentifiedChannelEnd`] plus a pair of
Same here. I think what the method does should be specified first, and then mention the types that the method expects.

2022-04-29 08:00 UTC, adizere commented
Thanks @mzabaluev and @seanchen1991 !

@seanchen1991 Please re-review and merge if you agree.

2022-04-29 13:28 UTC, seanchen1991 approved these changes

2022-04-29 13:28 UTC, merged