Hermes feature: Query the balance for a key
informalsystems/ibc-rs pull request #2232
Opened 2022-05-23 08:59 UTC by ljoss17

Closes: #912

## Description

This PR adds the sub command 'balance' to the command 'keys' to Hermes.

Usage :
```
hermes keys balance [chain_id] [keyname]
```

______

### PR author checklist:
- [x] Added changelog entry, using [`unclog`](https://github.com/informalsystems/unclog).
- [ ] Added tests: integration (for Hermes) or unit/mock tests (for modules). 
- [x] Linked to GitHub issue.
- [x] Updated code comments and guide (e.g., `guide/`).

### Reviewer checklist:

- [ ] Reviewed `Files changed` in the GitHub PR explorer.
- [ ] Manually tested (in case integration/unit/mock tests are absent).

2022-05-23 13:39 UTC, seanchen1991 reviewed
Left a couple of suggestions regarding messaging and documentation, but otherwise it looks good! 🙂

2022-05-23 13:39 UTC, seanchen1991 commented on relayer-cli/src/commands/keys/balance.rs
> +            Err(e) => Output::error(format!("{}", e)).exit(),
We should perhaps add some additional context to this error message, something like:
```suggestion
            Err(e) => Output::error(format!("there was a problem querying the chain balance: {}", e)).exit(),
```

2022-05-23 13:39 UTC, seanchen1991 commented on relayer-cli/src/commands/keys/balance.rs
> +
I think reiterating the documentation for this command in a doc comment for the struct helps other developers, i.e. they won't need to go and browse the guide to figure out what this command does. 

Here's an example from another command:
https://github.com/informalsystems/ibc-rs/blob/01145a1c48c0dc6e3e437492ba80d33962bcb65b/relayer-cli/src/commands/create/channel.rs#L27-L43

2022-05-23 15:07 UTC, seanchen1991 approved these changes

2022-05-23 15:38 UTC, ljoss17 commented on relayer-cli/src/commands/keys/balance.rs
> +    keyname: String,
Indeed, I realized this after I updated the error log of the command.
What I am not clear about is the usage of the query_balance method which takes the wallet name from the configuration file. If it is useful for many cases, I would tend to be more favorable for the option 2.

2022-05-24 09:06 UTC, romac commented on relayer-cli/src/commands/keys/balance.rs
> +            .unwrap_or_else(exit_with_unrecoverable_error);
```suggestion
       spawn_chain_runtime(config, &self.chain_id).unwrap_or_else(exit_with_unrecoverable_error);
```

2022-05-24 12:51 UTC, ljoss17 commented on relayer-cli/src/commands/keys/balance.rs
> +    keyname: String,
The option to modify the query_balance method to accept a key name as an Option. If None is given, the account is retrieved from the configuration file.

2022-05-25 12:49 UTC, romac requested changes
Very nice! Left a couple suggestions for improvement but otherwise it looks great 🎉

2022-05-25 12:49 UTC, romac commented on guide/src/commands/keys/index.md
> +    keyname                   key name
```suggestion
    key_name                  key name
```

2022-05-25 12:49 UTC, romac commented on guide/src/commands/keys/index.md
> +```
Can you please also add an example when the `--json` flag is supplied?

2022-05-25 12:49 UTC, romac commented on relayer-cli/src/commands/keys/balance.rs
> +    key_name: String,
This flag should be optional and use the default key when omitted. Please mention it as well in the help message and in the guide.

2022-05-30 10:59 UTC, romac approved these changes
Great work!

2022-05-30 12:40 UTC, merged