relayer: Fix one-past-the-limit flaw in message batching
informalsystems/ibc-rs pull request #2480
Opened 2022-07-29 14:56 UTC by mzabaluev

Closes: #2477

## Description

Prevent the batch data size from exceeding the given tx size limit.
Previous code pushed the offending last message to the end of the tx,
resulting in an oversized transaction.

______

### PR author checklist:
- [ ] Added changelog entry, using [`unclog`](https://github.com/informalsystems/unclog).
- [ ] Added tests: integration (for Hermes) or unit/mock tests (for modules).
- [x] Linked to GitHub issue.
- [ ] Updated code comments and documentation (e.g., `docs/`).
- [x] Tagged *one* reviewer who will be the one responsible for shepherding this PR.

### Reviewer checklist:

- [ ] Reviewed `Files changed` in the GitHub PR explorer.
- [ ] Manually tested (in case integration/unit/mock tests are absent).

2022-07-29 15:36 UTC, soareschen commented
Since `batch_messages` is now a pure function, let's have some unit tests that test the behavior of `batch_messages` directly without having to run the full integration test.

2022-07-29 15:52 UTC, ancazamfir commented
thanks for fixing this @mzabaluev !
Adding a note here, I checked the difference between the total length of the msgs in a batch and the final len of the serialized Tx and it's 278bytes. This is on a local gaia setup. We could probably recommend then for osmosis to allow for ~2k bytes for overhead until we figure out how to get that more exactly.

2022-07-29 15:53 UTC, ancazamfir approved these changes
Looks good! Thanks for the quick fix @mzabaluev !

2022-07-29 17:39 UTC, romac requested changes
Nice! Let's just add some unit tests before merging, please :)

2022-08-01 13:43 UTC, seanchen1991 commented
Tangentially related, but I noticed that there's no need for the `batch_messages` function to return a `Result`, should we change the signature of the function to just return `Vec<Any>`?

2022-08-01 13:46 UTC, seanchen1991 approved these changes

2022-08-02 07:55 UTC, romac commented
Can we expand the unit tests a bit, eg. to test for corner cases etc?

2022-08-02 16:19 UTC, seanchen1991 commented
@romac I added a few more unit tests. Let me know if there are additional corner cases that you think should be covered 🙂

2022-08-03 09:35 UTC, romac approved these changes

2022-08-03 10:12 UTC, merged