fix message conversion and replace proof
informalsystems/ibc-rs pull request #2535
Opened 2022-08-05 17:16 UTC by yito88

Closes: #2534 

## Description
- Fix the conversion from `RawMsgTimeoutOnClose` to set `proof_close` to `other_proof` in `MsgTimeoutOnClose`
- Replace the proof to be used for the channel verification

______

### PR author checklist:
- [ ] Added changelog entry, using [`unclog`](https://github.com/informalsystems/unclog).
- [ ] Added tests: integration (for Hermes) or unit/mock tests (for modules).
- [ ] Linked to GitHub issue.
- [ ] Updated code comments and documentation (e.g., `docs/`).
- [ ] Tagged *one* reviewer who will be the one responsible for shepherding this PR.

### Reviewer checklist:

- [ ] Reviewed `Files changed` in the GitHub PR explorer.
- [ ] Manually tested (in case integration/unit/mock tests are absent).

2022-08-05 19:42 UTC, hu55a1n1 requested changes
Thanks for the PR @yito88! Nice catch! :ok_hand: 
LGTM, but we're missing a .changelog entry. Please feel free to add one based on [these guidelines](https://github.com/informalsystems/ibc-rs/blob/master/CONTRIBUTING.md#changelog) otherwise we'll add one ourselves and hopefully merge early next week. 

PS: I think we would be able to avoid such bugs in the future by converting the `Proofs` struct into an enum based on the suggestion presented here -> https://github.com/informalsystems/ibc-rs/issues/1696#issue-1084534755, but let's do that in a future PR.

2022-08-05 20:29 UTC, yito88 commented
@hu55a1n1 Thank you for reviewing! I've added the change log.
#1696 suggestion sounds better!

2022-08-08 16:17 UTC, plafer commented
Good catch @yito88 , thank you for this! Could you please add a test to make sure there are no regressions on this when we do refactor the `Proofs` object?

2022-08-08 18:38 UTC, plafer approved these changes
Thank you!

2022-08-10 09:06 UTC, hu55a1n1 approved these changes
:pray:

2022-08-10 10:44 UTC, merged