Use abci-tag proc_macro for event attributes
informalsystems/ibc-rs pull request #276
Opened 2022-12-01 16:04 UTC by DaviRain-Su

Closes: #214 

## Description

This is my implementation of the `abci_tag proco marco` implementation of the feeling that there is still a toy Everyone see what other improvements, this implementation is to solve the problems raised in this issue.

______

### PR author checklist:
- [ ] Added changelog entry, using [`unclog`](https://github.com/informalsystems/unclog).
- [ ] Added tests.
- [ ] Linked to GitHub issue.
- [ ] Updated code comments and documentation (e.g., `docs/`).
- [ ] Tagged *one* reviewer who will be the one responsible for shepherding this PR.

### Reviewer checklist:

- [ ] Reviewed `Files changed` in the GitHub PR explorer.
- [ ] Manually tested (in case integration/unit/mock tests are absent).

2022-12-09 21:15 UTC, plafer requested changes
Thank you for this!

Could you also implement the change for 

- the structs found in `core::ics02_client::events`
- `ModuleEventAttribute` in `crate::events`

2022-12-09 21:15 UTC, plafer commented on crates/ibc/abci-tag/Cargo.toml
> +name = "abci-tag-proc-marco"
```suggestion
name = "abci-event-attr-key-proc-macro"
```

2022-12-09 21:15 UTC, plafer commented on crates/ibc/abci-tag/src/lib.rs
> +pub fn abci_tag(args: TokenStream, item: TokenStream) -> TokenStream {
```suggestion
pub fn abci_event_attr_key(args: TokenStream, item: TokenStream) -> TokenStream {
```

Could please change the name? I find this more descriptive.

2022-12-09 21:15 UTC, plafer commented on crates/ibc/abci-tag/src/lib.rs
> +            }
This is the old way to do it. Can you have the return value be as it was, e.g. 

```rust
impl From<PortIdAttribute> for abci::EventAttribute {
    fn from(attr: PortIdAttribute) -> Self {
        (PORT_ID_ATTRIBUTE_KEY, attr.port_id.as_str()).into()
    }
}
```

2022-12-12 11:34 UTC, romac commented
May I ask what problem this is solving and what's the scope for this? Is it only used to derive the From implementation? To me it sounds a bit overkill to introduce a whole new crate and a proc macro to save on 4 lines of code per event that won't change substantially in the future.

2022-12-12 11:38 UTC, romac commented
How we really want to save on those 4 lines, how about using a declarative macro instead? eg.

```rust
event_attr!(PortIdAttribute, PORTID_ATTR_KEY, port_id);
```

2022-12-12 12:37 UTC, plafer commented
I agree... I even prefer no declarative macro at all since it's just clearer what is being implemented for the struct.

Should we just close this PR and the issue? @romac @hu55a1n1 WDYT?

2022-12-12 12:44 UTC, hu55a1n1 commented
What I liked about the proc v/s declarative macro approach was that you didn't have to specify anything other than the attr key const, but I agree this is overkill as there are more additions in the PR than there are deletions (`+104 −87`). :+1:

2022-12-12 12:57 UTC, plafer commented
Thank you @DaviRain-Su for this. Unfortunately we'll close it for the reasons discussed.

2022-12-12 12:57 UTC, closed without merging

2022-12-12 12:57 UTC, DaviRain-Su commented
> Thank you @DaviRain-Su for this. Unfortunately we'll close it for the reasons discussed.

Understand