Add release script from tendermint-rs
informalsystems/ibc-rs pull request #473
Opened 2020-12-23 18:44 UTC by thanethomson

In releasing the `ibc` and `ibc-proto` crates, I used this script to speed things up a little (taken from the tendermint-rs release script).

---

For contributor use:

- [ ] Updated the __Unreleased__ section of [CHANGELOG.md](https://github.com/informalsystems/ibc-rs/blob/master/CHANGELOG.md) with the issue.
- [ ] If applicable: Unit tests written, added test to CI.
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Updated relevant documentation (`docs/`) and code comments.
- [ ] Re-reviewed `Files changed` in the Github PR explorer.

2020-12-23 18:44 UTC, thanethomson commented on release.sh
> +DEFAULT_CRATES="ibc-proto ibc"
This is the only difference from the tendermint-rs release script.

2020-12-24 23:20 UTC, romac requested changes
Great stuff! Just left a couple remarks to adapt the comments for ibc-rs.

See also: https://github.com/informalsystems/ibc-rs/issues/474

2020-12-24 23:20 UTC, romac commented on release.sh
> +#   ./release.sh proto tendermint
```suggestion
#   # Just release the ibc-proto and ibc crates, but nothing else
#   ./release.sh ibc-proto ibc
```

2020-12-24 23:20 UTC, romac commented on release.sh
> +# /tmp/tendermint-rs-release/${TODAY}/${CRATE}, where ${TODAY} is today's date
```suggestion
# /tmp/ibc-rs-release/${TODAY}/${CRATE}, where ${TODAY} is today's date
```

2021-01-07 15:04 UTC, romac approved these changes

2021-01-07 15:10 UTC, merged