Fix communication with runtime for build_header and misbehaviour
informalsystems/ibc-rs pull request #858
Opened 2021-04-27 19:56 UTC by ancazamfir

Closes: #XXX

## Description
Fixes are included for the following issues:
- when errors are detected in the runtime they should be sent via the channel to the caller. This is generally the case with all our APIs, except:
  - `build_header()`
  - `check_misbehaviour()`
- the update client event is not properly decoded (e.g. by the `hermes listen` command) when header field is `None`
- `some_attribute` macro returns error when the field is not present (the intent is to return `None` when field is missing, `Some(obj)` if attribute parses ok, bubble up error otherwise)

These issues were discovered when @andynog was testing hermes on `akashnet-2` that is using an older SDK version (v0.41.3): no header in update client event, causing misbehavior check to return error (fine) that it is then improperly handled (bad).

______

For contributor use:

- [ ] Updated the __Unreleased__ section of [CHANGELOG.md](https://github.com/informalsystems/ibc-rs/blob/master/CHANGELOG.md) with the issue.
- [ ] If applicable: Unit tests written, added test to CI.
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Updated relevant documentation (`docs/`) and code comments.
- [ ] Re-reviewed `Files changed` in the Github PR explorer.

2021-04-28 13:42 UTC, andynog requested changes
I'm still getting an error running the command. Please see comments.

2021-04-28 13:43 UTC, andynog commented
I'm still getting a panic when running the command
```
hermes misbehaviour akashnet-2 07-tendermint-9
Apr 28 13:39:03.958  INFO ibc_relayer_cli::commands: Using default configuration from: '.hermes/config.toml'
Apr 28 13:39:03.978  INFO ibc_relayer::event::monitor: running listener chain.id=akashnet-2
Apr 28 13:39:04.021  INFO ibc_relayer::event::monitor: running listener chain.id=cosmoshub-4
Apr 28 13:39:04.127  INFO ibc_relayer::foreign_client: checking misbehaviour for consensus state heights [Height { revision: 4, height: 6025668 }, Height { revision: 4, height: 6014305 }, Height { revision: 4, height: 6013894 }, Height { revision: 4, height: 6013767 }, Height { revision: 4, height: 6013743 }, Height { revision: 4, height: 6002967 }, Height { revision: 4, height: 6002960 }, Height { revision: 4, height: 6002848 }, Height { revision: 4, height: 6002818 }, Height { revision: 4, height: 6002756 }, Height { revision: 4, height: 6002693 }, Height { revision: 4, height: 6002684 }, Height { revision: 4, height: 6002649 }]
The application panicked (crashed).
Message:  called `Result::unwrap()` on an `Err` value: Error(Context { kind: Misbehaviour("missing header in update client event cosmoshub-4"), source: None, backtrace: Some(   0: <ibc_relayer::light_client::tendermint::LightClient as ibc_relayer::light_client::LightClient<ibc_relayer::chain::cosmos::CosmosSdkChain>>::check_misbehaviour
   1: ibc_relayer::chain::runtime::ChainRuntime<C>::run
   2: std::sys_common::backtrace::__rust_begin_short_backtrace
   3: core::ops::function::FnOnce::call_once{{vtable.shim}}
   4: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys/unix/thread.rs:71:17
   5: start_thread
   6: clone
) })
Location: /home/ubuntu/relayer/ibc-rs/relayer/src/chain/runtime.rs:118

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
Error: could not run misbehaviour detection for 07-tendermint-9: error raised while submitting the misbehaviour evidence: failed to build misbehaviour failed to send or receive through channel: receiving on an empty and disconnected channel
```

2021-04-28 13:59 UTC, ancazamfir commented
> I'm still getting a panic when running the command

Just to make sure, are you running hermes from this PR branch? The update client on cosmoshub is orthogonal to the misbehaviour command you issue for the akashnet client. And no issue with the warnings, we are not interested in those events so we don't decode them. Will fix the warning message with something better.

When initially ran, the misbehaviour command goes over all consensus states and verifies them (retrieves the update client event and verifies the header). What I see locally, we exit gracefully on the first check if headers are not included in the update client events.

2021-04-28 14:05 UTC, andynog commented
Yes, I've updated hermes with the latest from this branch.

2021-04-28 16:31 UTC, ancazamfir commented
Could I have access to the setup? config file?

2021-04-28 18:46 UTC, andynog commented
It's all good, tested it properly again and I don't get the panic anymore just the error message.

```
hermes misbehaviour akashnet-2 07-tendermint-9
Apr 28 18:12:43.309  INFO ibc_relayer_cli::commands: Using default configuration from: '.hermes/config.toml'
Apr 28 18:12:43.354  INFO ibc_relayer::event::monitor: running listener chain.id=akashnet-2
Apr 28 18:12:43.380  INFO ibc_relayer::event::monitor: running listener chain.id=cosmoshub-4
Apr 28 18:12:43.486  INFO ibc_relayer::foreign_client: checking misbehaviour for consensus state heights [Height { revision: 4, height: 6026497 }, Height { revision: 4, height: 6025668 }, Height { revision: 4, height: 6014305 }, Height { revision: 4, height: 6013894 }, Height { revision: 4, height: 6013767 }, Height { revision: 4, height: 6013743 }, Height { revision: 4, height: 6002967 }, Height { revision: 4, height: 6002960 }, Height { revision: 4, height: 6002848 }, Height { revision: 4, height: 6002818 }, Height { revision: 4, height: 6002756 }, Height { revision: 4, height: 6002693 }, Height { revision: 4, height: 6002684 }, Height { revision: 4, height: 6002649 }]
Error: could not run misbehaviour detection for 07-tendermint-9: error raised while checking for misbehaviour evidence: failed to build misbehaviour error raised while submitting the misbehaviour evidence: missing header in update client event cosmoshub-4
```

2021-04-28 18:47 UTC, andynog approved these changes

2021-04-29 13:50 UTC, ancazamfir commented
Merging this now, seeing also the `build_header()` panics when testing the client refresh (i set trusting period low in the config, 40 sec so this fails with expired trusted state)

2021-04-29 13:50 UTC, merged