Remove regex requirement
informalsystems/ibc-rs pull request #876
Opened 2023-09-22 14:47 UTC by rnbguy

Closes: #875

## Description

- Removes any _regex_ requirement
- Removes `safe_regex` which is breaking our docsrs builds

______

### PR author checklist:
- [ ] Added changelog entry, using [`unclog`](https://github.com/informalsystems/unclog).
- [ ] Added tests.
- [x] Linked to GitHub issue.
- [ ] Updated code comments and documentation (e.g., `docs/`).
- [ ] Tagged *one* reviewer who will be the one responsible for shepherding this PR.

### Reviewer checklist:

- [ ] Reviewed `Files changed` in the GitHub PR explorer.
- [ ] Manually tested (in case integration/unit/mock tests are absent).

2023-09-25 08:29 UTC, soareschen requested changes
We need to write tests to ensure that the new implementation works as expected.

2023-09-25 08:29 UTC, soareschen commented on crates/ibc/src/applications/transfer/coin.rs
> +            .filter(|(_, denom)| {
I think filter means that you will exclude the invalid characters, but the result would be valid. In the original case, invalid characters will cause the method to fail.

2023-09-25 08:29 UTC, soareschen commented on crates/ibc/src/applications/transfer/coin.rs
> +                    !matches!(x, 'a'..='z' | 'A'..='Z' | '0'..='9' | '/' | ':' | '\\' | '.' | '_' | '-')
I think `\\` was used as an escape for `\`, which is an escape for `.` in the original regex.

2023-09-25 11:27 UTC, rnbguy commented
> We need to write tests to ensure that the new implementation works as expected.

Yea. Tests are coming :slightly_smiling_face: I wanted to confirm the parsing logic before that.

2023-09-27 00:47 UTC, Farhad-Shabani requested changes

2023-09-27 00:47 UTC, Farhad-Shabani commented on crates/ibc/src/applications/transfer/coin.rs
> +        DT: Into<D>,
A note regarding these bounds, as this method would get available to our users too (not only for the tests)

Although they've made improvements in cleaning up test arguments, and at first glance, it seems to give users more flexibility, it's important to note that there are situations where both `amount` and `denom` might come from either parsing a string or using `TryFrom`. This means not all conversions can simply turn into `Amount` and `D` so users may obtain them from conversions that might fail.

In fact, we even shouldn’t use `TryFrom` or similar restrictions in this specific situation. As particularly `Coin` is generic over denoms and We can't foresee how hosts will obtain this data. So any restrictions will assume a certain approach, which may not always work. Also, e.g. in cases like [here](https://github.com/cosmos/ibc-rs/blob/1aa853bb646d37aab3848096b4221450f3a2e760/crates/ibc/src/applications/transfer/coin.rs#L94-L97) and [here](https://github.com/cosmos/ibc-rs/blob/dc8e4161dd5e00a2031cf3feb58dad1ed7e26bdb/crates/ibc/src/applications/transfer/packet.rs#L46), it is easier to work with the own types.

Btw, if still want to keep our tests args as is, Perhaps we should move this method (as a helper) under the `tests` module and only have it for the `RawCoin` type. Wdyt?

2023-09-27 00:47 UTC, Farhad-Shabani commented on crates/ibc/src/applications/transfer/coin.rs
>          // https://github.com/cosmos/cosmos-sdk/blob/v0.45.5/types/coin.go#L760-L762
```suggestion
        // https://github.com/cosmos/cosmos-sdk/blob/v0.47.5/types/coin.go#L838-L840
```

2023-09-27 00:47 UTC, Farhad-Shabani commented on crates/ibc/src/applications/transfer/coin.rs
> +    #[rstest]
Good to include a case for checking lower/uppers case sensitivity.

2023-09-27 00:47 UTC, Farhad-Shabani commented on crates/ibc/src/applications/transfer/coin.rs
> +            })
Here we can simplify the implementation and use the same approach as [here](https://github.com/cosmos/ibc-rs/blob/dc8e4161dd5e00a2031cf3feb58dad1ed7e26bdb/crates/ibc/src/core/ics24_host/identifier/validate.rs#L22-L31) by defnining e.g. `VALID_DENOM_CHARACTERS` , after which the `!denom.is_empty()` check won’t be needed anymore too. Even we might be able to decouple checks and filter of the amount from the denom. Appreciate a further look on this.

Will looks like something like this:

```rust
const VALID_DENOM_CHARACTERS: &str = "/:._-";

let (amount, denom) = coin_str
            .chars()
            .position(|x| !x.is_numeric())
            .map(|index| coin_str.split_at(index))
            .filter(|(amount, _)| !amount.is_empty())
            .filter(|(_, denom)| {
                denom
                    .chars()
                    .all(|x| x.is_alphanumeric() || VALID_DENOM_CHARACTERS.contains(x))
            })
            .ok_or_else(|| TokenTransferError::InvalidCoin {
                coin: coin_str.to_string(),
            })?;
```

2023-09-27 13:28 UTC, Farhad-Shabani approved these changes
Good job @rnbguy. Thanks 👌🏻

2023-09-27 17:58 UTC, soareschen approved these changes

2023-09-27 19:07 UTC, merged