worker for Channel
informalsystems/ibc-rs pull request #924
Opened 2021-05-11 09:42 UTC by cezarad

Closes: #822

## Description

- added a worker for  channel 
- added query_connection_channels

To execute  ./scripts/dev-env ~/.hermes/config.toml ibc-0 ibc-1
- case A: 
      1. create a connection : ` hermes create connection ibc-0 ibc-1 `
      2. start the relayer ` hermes start-multi `    
      3. send `hermes tx raw chan-open-init ibc-0 ibc-1 connection-0 transfer transfer `
- Case B: 
     1. create a connection : ` hermes create connection ibc-0 ibc-1 `
     2. send `hermes tx raw chan-open-init ibc-0 ibc-1 connection-0 transfer transfer `
     3. start the relayer ` hermes start-multi ` 

______

For contributor use:

- [ ] Updated the __Unreleased__ section of [CHANGELOG.md](https://github.com/informalsystems/ibc-rs/blob/master/CHANGELOG.md) with the issue.
- [ ] If applicable: Unit tests written, added test to CI.
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Updated relevant documentation (`docs/`) and code comments.
- [ ] Re-reviewed `Files changed` in the Github PR explorer.

2021-05-14 09:19 UTC, ancazamfir commented
Changed to draft to cleanup my changes

2021-05-25 17:22 UTC, adizere approved these changes
Massive work Anca & Cezara!

Had a look over the code and looks good, the tests also run fine. I am still running some further tests with `gm` but I'm approving already since I consider this done. Mind the "TODO before merge" remark.

2021-05-26 08:25 UTC, romac commented on docs/architecture/adr-002-ibc-relayer.md
> +    Packets,
```suggestion
    All,
    Packets,
```

2021-05-26 10:36 UTC, ancazamfir commented on relayer/src/worker/channel.rs
> +                                retry_with_index(retry_strategy::uni_chan_path(), |index| {
renamed to `worker_default_strategy`

2021-05-26 10:37 UTC, ancazamfir commented on relayer/src/supervisor.rs
> +                        event.clone().channel_attributes().unwrap(),
missed this one

2021-05-26 10:39 UTC, ancazamfir commented on relayer/src/channel.rs
> +            assert!(self.dst_channel_id().is_some());
missed this also, thanks!

2021-05-26 10:47 UTC, ancazamfir commented on relayer/src/channel.rs
> +            //TODO  detect version from event
Removed and added explanation. We cannot do much here but the message builders figure it out.

2021-05-26 10:48 UTC, ancazamfir commented on relayer/src/channel.rs
> +            //TODO  how to get the order from event
Removed and added explanation. We cannot do much here but the message builders figure it out.

2021-05-26 11:42 UTC, romac approved these changes

2021-05-26 11:53 UTC, ancazamfir requested changes
change strategy in CI

2021-05-26 13:07 UTC, merged